Repository ScilifelabDataCentre/serve, pull requests merged in 2023-11, with the labels that each got.

#95 Bugfix/SS 637 adding tags with spaces for apps not working properly
  apps/views.py
  scripts/admin_token.py
  scripts/run_web.sh
  templates/apps/update.html
  templates/common/autocomplete.html
  templates/portal/apps.html
  templates/projects/overview.html
Labels: bug

#93 SS 410 create a homepage with a new look
  news/LICENSE
  news/MANIFEST.in
  news/README.md
  news/__init__.py
  news/admin.py
  news/apps.py
  news/migrations/0001_initial.py
  news/migrations/__init__.py
  news/models.py
  news/setup.py
  news/tasks.py
  news/tests.py
  news/urls.py
  news/views.py
  portal/tests.py
  portal/views.py
  static/css/serve-colors.css
  static/css/serve-text.css
  static/vendor/aos-2.3.4-dist/css/aos.css
  static/vendor/aos-2.3.4-dist/js/aos.js
  studio/settings.py
  studio/urls.py
  templates/base.html
  templates/common/common_head.html
  templates/common/navbar.html
  templates/models/index.html
  templates/portal/apps.html
  templates/portal/home.html
  templates/portal/news.html
Labels: enhancement, new feature

#94 SS 654 serve apps should have copy api endpoint button
  templates/base.html
  templates/portal/apps.html
  templates/projects/overview.html
Labels: enhancement, new feature

#100 Hotfix/readiness probe in shinyproxy
  charts/apps/shinyproxy/chart/templates/deployment.yaml
Labels: new feature

#99 Added delete develop-apps task that runs every day a 4 am.
  apps/tasks.py
  fixtures/periodic_tasks_fixtures.json
Labels: new feature

#103 Hotfix/add db reset option
  docker-compose.yaml
  scripts/run_web.sh
Labels: new feature

#106 SS-701 - Public apps should be visible when logged out
  portal/views.py
Labels: bug

#105 SS-694 Create user profile page
  api/openapi/lookups_api.py
  api/openapi/urls.py
  studio/urls.py
  studio/views.py
  templates/common/navbar.html
  templates/user/profile.html
Labels: new feature

#107 SS 677 disable model deployment functionality
  apps/views.py
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  static/css/serve-utilities.css
  templates/apps/update.html
  templates/projects/overview.html
Labels: change

#108 SS-721 - minio is setting persistent volume as none by default
  .pre-commit-config.yaml
  fixtures/projects_templates.json
Labels: bug

#109 Bugfix/shiny dash app port
  charts/apps/dash/chart/templates/deployment.yaml
  charts/apps/dash/chart/templates/service.yaml
  charts/apps/shiny/chart/templates/deployment.yaml
  charts/apps/shiny/chart/templates/service.yaml
Labels: bug

#110 Bugfix/shiny proxy configmap not dynamic
  charts/apps/shinyproxy/chart/templates/deployment.yaml
  charts/apps/shinyproxy/chart/values.yaml
Labels: bug

#112 SS-705 minor adjustments in project dashboard
  fixtures/apps_fixtures.json
  templates/apps/create.html
  templates/apps/update.html
  templates/projects/overview.html
  templates/registration/login.html
Labels: enhancement

#111 SS-692 minor adjustments of texts
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-homepage.cy.js
  cypress/e2e/ui-tests/test-login.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-project-as-superuser.cy.js
  cypress/e2e/ui-tests/test-public-apps-page.cy.js
  cypress/e2e/ui-tests/test-public-models-page.cy.js
  cypress/e2e/ui-tests/test-signup.cy.js
  models/tests.py
  portal/tests.py
  portal/views.py
  projects/tests/test_project_view.py
  static/css/serve-elements.css
  templates/base.html
  templates/common/footer.html
  templates/common/navbar.html
  templates/portal/about.html
  templates/portal/home.html
Labels: enhancement
