Repository ScilifelabDataCentre/serve, pull requests merged in 2023-10, with the labels that each got.

#76 Update admin views, add shiny proxy and add subdomain functionality
  apps/models.py
  apps/tasks.py
  apps/urls.py
  apps/views.py
  charts/apps/shinyproxy/chart/Chart.yaml
  charts/apps/shinyproxy/chart/templates/_helpers.tpl
  charts/apps/shinyproxy/chart/templates/configmap.yaml
  charts/apps/shinyproxy/chart/templates/deployment.yaml
  charts/apps/shinyproxy/chart/templates/hooks.yaml
  charts/apps/shinyproxy/chart/templates/ingress.yaml
  charts/apps/shinyproxy/chart/templates/service.yaml
  charts/apps/shinyproxy/chart/values.yaml
  charts/apps/shinyproxy/config.json
  cypress/e2e/db-seed-superuser.sh
  cypress/e2e/setup-scripts/seed_superuser.py
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-project-as-superuser.cy.js
  cypress/fixtures/users.json
  fixtures/apps_fixtures.json
  models/views.py
  projects/urls.py
  projects/views.py
  static/images/logos/apps/shinyproxyapp-logo.png
  studio/settings.py
  studio/views.py
  templates/apps/create.html
  templates/apps/update.html
  templates/common/common_head.html
  templates/projects/settings.html
Labels: enhancement, new feature

#77 SS-606, SS-534 - adjust default flavor, make two project templates
  cypress/e2e/ui-tests/test-homepage.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/support/commands.js
  fixtures/appcats_fixtures.json
  fixtures/apps_fixtures.json
  fixtures/projects_templates.json
  portal/urls.py
  portal/views.py
  projects/admin.py
  projects/views.py
  studio/settings.py
  templates/apps/create.html
  templates/apps/update.html
  templates/base.html
  templates/common/footer.html
  templates/common/navbar.html
  templates/portal/about.html
  templates/projects/overview.html
  templates/projects/project_templates.html
  templates/wiki/base.html
Labels: enhancement, new feature

#80 SS-409 css review and cleanup
  fixtures/projects_templates.json
  static/css/serve-colors.css
  static/css/serve-elements.css
  static/css/serve-text.css
  static/css/serve-utilities.css
  static/css/text.css
  templates/admin/base_site.html
  templates/apps/create.html
  templates/apps/update.html
  templates/base.html
  templates/common/common_fonts.html
  templates/common/common_head.html
  templates/common/footer.html
  templates/common/navbar.html
  templates/portal/about.html
  templates/projects/grant_revoke_access.html
  templates/projects/index.html
  templates/projects/project_create.html
  templates/projects/project_templates.html
  templates/projects/settings.html
  templates/registration/password_change_form.html
Labels: enhancement

#81 SS-585 network fixes and adding seccomp profile
  apps/tasks.py
  apps/views.py
  charts/apps/custom-app/chart/values.yaml
  charts/apps/dash/chart/values.yaml
  charts/apps/jupyter-lab/chart/values.yaml
  charts/apps/minio/chart/templates/project-s3-deployment.yaml
  charts/apps/mlflow-serve/chart/values.yaml
  charts/apps/mlflow/chart/values.yaml
  charts/apps/netpolicy/chart/templates/default.yaml
  charts/apps/pytorch-serve/chart/values.yaml
  charts/apps/rstudio/chart/values.yaml
  charts/apps/shiny/chart/values.yaml
  charts/apps/shinyproxy/chart/templates/configmap.yaml
  charts/apps/shinyproxy/chart/templates/deployment.yaml
  charts/apps/shinyproxy/chart/templates/hooks.yaml
  charts/apps/shinyproxy/chart/values.yaml
  charts/apps/tensorflow-serve/chart/values.yaml
  charts/apps/vscode/chart/values.yaml
  fixtures/projects_templates.json
  templates/apps/create.html
Labels: enhancement, Security

#84 SS-583 custom css for user guide
  static/css/serve-elements.css
  static/css/serve-user-guide.css
  templates/wiki/admin_menu.html
  templates/wiki/base.html
Labels: enhancement

#89 Hotfix/workflow bug
  .github/workflows/e2e-tests.yaml
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  fixtures/projects_templates.json
Labels: bug, cicd

#87 SS-582 solve the issue with images in user guide
  Dockerfile
Labels: bug

#90 SS 599 make sure we use our own images from serve images repo
  charts/apps/jupyter-lab/chart/values.yaml
  charts/apps/mlflow-serve/chart/values.yaml
  charts/apps/mlflow/chart/values.yaml
  charts/apps/pytorch-serve/chart/values.yaml
  charts/apps/rstudio/chart/values.yaml
  charts/apps/shinyproxy/chart/templates/deployment.yaml
  charts/apps/tensorflow-serve/chart/values.yaml
  fixtures/projects_templates.json
Labels: Security
