Repository ScilifelabDataCentre/serve, pull requests merged in 2023-12, with the labels that each got.

#116 Feature/SS-131 python model serve app
  charts/apps/python-serve/chart/Chart.yaml
  charts/apps/python-serve/chart/templates/deployment.yaml
  charts/apps/python-serve/chart/templates/ingress.yaml
  charts/apps/python-serve/chart/templates/nginx_conf.yaml
  charts/apps/python-serve/chart/templates/service.yaml
  charts/apps/python-serve/chart/values.yaml
  charts/apps/python-serve/config.json
  fixtures/apps_fixtures.json
  fixtures/projects_templates.json
  static/images/logos/apps/python-serve-logo.png
  templates/projects/overview.html
Labels: new feature

#115 SS-601 and 662 emails
  common/admin.py
  common/forms.py
  common/migrations/0002_emailverificationtable.py
  common/models.py
  common/signals.py
  common/tests.py
  common/urls.py
  common/views.py
  conftest.py
  cypress/e2e/ui-tests/test-login-account-handling.cy.js
  cypress/e2e/ui-tests/test-login.cy.js
  cypress/e2e/ui-tests/test-signup.cy.js
  docker-compose.yaml
  studio/settings.py
  studio/views.py
  templates/common/footer.html
  templates/registration/password_reset_email.html
  templates/registration/registration_complete.html
  templates/registration/verify.html
  templates/registration/verify_email.html
Labels: enhancement

#119 Hotfix/shiny proxy internet egress
  charts/apps/shinyproxy/chart/templates/configmap.yaml
  charts/apps/shinyproxy/chart/templates/deployment.yaml
  charts/apps/shinyproxy/chart/templates/hooks.yaml
  charts/apps/shinyproxy/chart/templates/ingress.yaml
  fixtures/objecttype_fixtures.json
  fixtures/projects_templates.json
Labels: bug

#120 Hotfix email domain name
  common/models.py
  fixtures/projects_templates.json
  templates/registration/password_reset_email.html
  templates/registration/verify_email.html
Labels: bug

#114 Feature/kube event listener
  apps/controller.py
  apps/tasks.py
  apps/views.py
  fixtures/periodic_tasks_fixtures.json
  requirements.txt
Labels: new feature
