Repository ScilifelabDataCentre/serve, pull requests merged in 2024-08, with the labels that each got.

#208 SS-1043 Update app creation template header
  apps/views.py
  templates/apps/create_base.html
Labels: enhancement

#210 SS-1072 changes to tags and description fields
  apps/constants.py
  apps/forms/custom.py
  apps/forms/dash.py
  apps/forms/shiny.py
  apps/forms/tissuumaps.py
  apps/migrations/0003_alter_customappinstance_tags_alter_dashinstance_tags_and_more.py
  apps/models/base/social_mixin.py
Labels: enhancement

#209 SS-1070 update permissions handling
  apps/constants.py
  apps/forms/custom.py
  apps/forms/dash.py
  apps/forms/shiny.py
  apps/migrations/0004_alter_customappinstance_access_and_more.py
  apps/models/app_types/custom.py
  apps/models/app_types/dash.py
  apps/models/app_types/jupyter.py
  apps/models/app_types/rstudio.py
  apps/models/app_types/shiny.py
  apps/models/app_types/tissuumaps.py
  apps/models/app_types/vscode.py
  templates/apps/create_base.html
Labels: enhancement

#206 SS-1071 shinyproxy form enchancement
  apps/forms/shiny.py
  projects/views.py
Labels: enhancement, change

#211 Feature/SS-1067 subdomain enchancements
  api/urls.py
  api/views.py
  apps/admin.py
  apps/forms/base.py
  apps/forms/custom.py
  apps/helpers.py
  apps/migrations/0006_subdomain_is_created_by_user_and_more.py
  apps/models/base/base.py
  apps/models/base/subdomain.py
  apps/signals.py
  apps/tests/test_forms.py
  apps/tests/test_subdomain_candidate.py
  apps/types_/subdomain.py
  apps/views.py
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  poetry.lock
  pyproject.toml
  static/js/htmx.min.js
  studio/settings.py
  templates/apps/create_base.html
  templates/apps/partials/subdomain_input.html
  templates/apps/partials/subdomain_input_group.html
  templates/apps/partials/subdomain_select.html
  templates/common/common_head.html
Labels: enhancement

#212 SS-1069-upd-forms-volumes
  apps/forms/tissuumaps.py
Labels: enhancement

#213 Shiny volume support
  apps/admin.py
  apps/migrations/0007_shinyinstance_path_shinyinstance_volume.py
  apps/migrations/0008_alter_shinyinstance_allow_container_reuse_and_more.py
  apps/migrations/0009_alter_customappinstance_volume_and_more.py
  apps/models/app_types/custom.py
  apps/models/app_types/shiny.py
  apps/models/app_types/tissuumaps.py
  apps/models/app_types/volume.py
  fixtures/apps_fixtures.json
Labels: enhancement

#214 Small UI changes to forms before 1.4.0
  apps/forms/tissuumaps.py
  apps/models/app_types/tissuumaps.py
  portal/views.py
  static/tagulous/adaptor/select2-3.js
  static/tagulous/adaptor/select2-4.js
  static/tagulous/tagulous.js
  templates/apps/create_base.html
Labels: bug
