Repository ScilifelabDataCentre/serve, pull requests merged in 2024-04, with the labels that each got.

#179 Add a field to app settings for source code URL
  apps/helpers.py
  apps/models.py
  apps/views.py
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  fixtures/apps_fixtures.json
  static/css/serve-elements.css
  static/js/apps_form.js
  studio/migrations/apps/0007_appinstance_source_code_url.py
  templates/apps/create.html
  templates/apps/update.html
  templates/common/app_card.html
Labels: new feature

#178 Add support for rendering records from Zenodo to collections
  collections_module/migrations/0002_collection_zenodo_community_id.py
  collections_module/models.py
  static/js/fetch_zenodo_community_entries.js
  templates/collections/collection.html
Labels: new feature

#180 SS 975 new solution for restoring apps
  apps/admin.py
  apps/tasks.py
  portal/views.py
Labels: new feature

#182 SS 632 option delete account
  common/migrations/0004_userprofile_deleted_on.py
  common/models.py
  docker-compose.yaml
  portal/views.py
  studio/helpers.py
  studio/settings.py
  studio/tests.py
  studio/urls.py
  studio/views.py
  templates/user/account_delete_form.html
  templates/user/account_deleted.html
  templates/user/profile.html
Labels: security, new feature

#184 SS-991 Job to handle deleted users
  common/tasks.py
  fixtures/intervals_fixtures.json
  fixtures/periodic_tasks_fixtures.json
Labels: enhancement, security

#185 SS-920 no email already exists
  apps/tasks.py
  common/forms.py
  common/models.py
  common/signals.py
  common/tasks.py
  common/tests.py
  common/views.py
  cypress/e2e/ui-tests/test-signup.cy.js
Labels: security, change

#187 SS-887-custom-404-page
  templates/404.html
Labels: enhancement

#186 Expanded end-to-end tests to include flavor addition, collections functionality and more
  cypress/e2e/db-seed-collections-user.sh
  cypress/e2e/setup-scripts/seed_collections_user.py
  cypress/e2e/setup-scripts/seed_deploy_app_user.py
  cypress/e2e/setup-scripts/seed_superuser.py
  cypress/e2e/ui-tests/test-collections.cy.js
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-project-as-superuser.cy.js
  cypress/e2e/ui-tests/test-public-apps-page.cy.js
  cypress/e2e/ui-tests/test-public-models-page.cy.js
  cypress/e2e/ui-tests/test-public-webpages.cy.js
  cypress/fixtures/users.json
  docs/.nojekyll
  docs/README.md
  docs/_navbar.md
  docs/cli.md
  docs/images/STACKn_overview.svg
  docs/images/apps-from-overview.gif
  docs/images/apps-from-side-panel.gif
  docs/images/create-project.gif
  docs/images/project-overview.gif
  docs/images/stackn_diagram.png
  docs/images/stackn_serve_overview.png
  docs/index.html
  docs/releasenotes.md
  docs/tutorial.md
  static/js/fetch_zenodo_community_entries.js
  templates/apps/logs.html
  templates/collections/collection.html
  templates/common/app_card.html
Labels: enhancement, cicd

#189 Added collections block on homepage and collections index page
  collections_module/urls.py
  collections_module/views.py
  cypress/e2e/ui-tests/test-collections.cy.js
  portal/views.py
  static/css/serve-elements.css
  templates/collections/collection.html
  templates/collections/index.html
  templates/common/footer.html
  templates/portal/home.html
Labels: enhancement

#181 Ss 990 deleted pvc still shown as an option for attaching to an app
  apps/views.py
Labels: bug

#188 SS-973 Pause dormant users
  common/management/commands/install_fixtures.py
  common/models.py
  common/tasks.py
  fixtures/groups_fixtures.json
  fixtures/periodic_tasks_fixtures.json
  studio/helpers.py
  studio/tests.py
Labels: security

#190 fixed error
  apps/views.py
Labels: bug

#191 Bugfix: correct URLs of project pages
  apps/tests/test_app_settings_view.py
  apps/tests/test_create_app_view.py
  apps/tests/test_delete_app_view.py
  apps/tests/test_get_status_view.py
  cypress/e2e/ui-tests/test-public-webpages.cy.js
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  projects/tests/test_grant_access_to_project_view.py
  projects/tests/test_revoke_access_to_project_view.py
  projects/tests/test_update_pattern_view.py
  projects/urls.py
  projects/views.py
  studio/urls.py
Labels: bug

#192 add database model for maintenance mode info
  common/admin.py
  common/context_processors.py
  common/migrations/0005_maintenancemode.py
  common/models.py
  customtags/templatetags/is_login_signup_disabled.py
  portal/tests.py
  studio/settings.py
  templates/common/footer.html
  templates/common/navbar.html
  templates/portal/home.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: new feature

#196 Fixed a number of minor bugs and added support for additional shiny app settings for admins
  apps/controller.py
  apps/helpers.py
  apps/views.py
  fixtures/apps_fixtures.json
  projects/models.py
  projects/urls.py
  projects/views.py
  templates/403.html
  templates/apps/create.html
  templates/apps/update.html
  templates/projects/settings.html
Labels: bug, enhancement
