Repository ScilifelabDataCentre/serve, pull requests merged in 2024-10, with the labels that each got.

#234 Add UI fields to set ephemeral storage for new flavors
  projects/forms.py
  projects/migrations/0005_alter_flavor_cpu_lim_alter_flavor_ephmem_lim_and_more.py
  projects/migrations/0006_alter_flavor_cpu_lim_alter_flavor_cpu_req_and_more.py
  projects/models.py
  projects/views.py
  templates/projects/settings.html
Labels: enhancement

#233 Combined apps and models page + small changes and bugfixes
  api/openapi/public_apps_api.py
  api/openapi/urls.py
  api/tests/test_openapi_public_apps.py
  apps/constants.py
  apps/forms/custom.py
  apps/forms/dash.py
  apps/forms/shiny.py
  apps/forms/tissuumaps.py
  apps/migrations/0013_alter_customappinstance_tags_alter_dashinstance_tags_and_more.py
  apps/migrations/0014_alter_customappinstance_path.py
  apps/models/app_types/custom.py
  apps/models/app_types/shiny.py
  apps/models/base/social_mixin.py
  apps/views.py
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-public-webpages.cy.js
  cypress/e2e/ui-tests/test-views-as-reader.cy.js
  fixtures/projects_templates.json
  portal/tests.py
  portal/urls.py
  portal/views.py
  pyproject.toml
  static/css/serve-user-guide.css
  studio/settings.py
  templates/common/footer.html
  templates/common/navbar.html
  templates/events/events.html
  templates/portal/apps.html
  templates/portal/home.html
Labels: bug, enhancement, change

#237 SS-1133 Added errors display for shiny site dir
  templates/apps/partials/srv_prepend_append_input_group.html
Labels: bug

#236 Added `shiny_site_dir` as a field that triggers redeployment
  apps/helpers.py
Labels: bug

#238 SS-342 Add new app type: Gradio
  apps/admin.py
  apps/app_registry.py
  apps/forms/__init__.py
  apps/forms/gradio.py
  apps/migrations/0015_tagulous_abstractcustomappinstance_tags_and_more.py
  apps/models/app_types/__init__.py
  apps/models/app_types/custom/__init__.py
  apps/models/app_types/custom/base.py
  apps/models/app_types/custom/custom.py
  apps/models/app_types/custom/gradio.py
  apps/tasks.py
  fixtures/apps_fixtures.json
  fixtures/projects_templates.json
  portal/views.py
  static/images/logos/apps/gradio-logo.svg
Labels: new feature

#240 SS-1167 streamlit app type
  apps/admin.py
  apps/app_registry.py
  apps/forms/__init__.py
  apps/forms/streamlit.py
  apps/migrations/0016_tagulous_streamlitinstance_tags_streamlitinstance.py
  apps/models/app_types/__init__.py
  apps/models/app_types/custom/streamlit.py
  fixtures/apps_fixtures.json
  fixtures/projects_templates.json
  static/images/logos/apps/streamlit-logo.svg
Labels: new feature

#242 Changes to project and app deletion routines
  apps/admin.py
  apps/tasks.py
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  fixtures/intervals_fixtures.json
  fixtures/periodic_tasks_fixtures.json
  projects/admin.py
  projects/migrations/0008_project_deleted_on.py
  projects/models.py
  projects/tasks.py
  templates/projects/settings.html
Labels: change

#244 Bugfix for duplicate display of shiny apps
  portal/views.py
Labels: bug
