Repository ScilifelabDataCentre/serve, pull requests merged in 2024-03, with the labels that each got.

#161 SS 950 apps fail if names contains comma
  apps/serialize.py
Labels: bug

#162 SS-955 updated startup script to update passwords
  scripts/admin_token.py
Labels: bug

#165 Bugfix/render correct apps in overview
  templates/apps/create.html
  templates/apps/update.html
  templates/projects/overview.html
Labels: bug

#166 update chart with ingress link only logic
  charts/apps/tissuumaps/chart/templates/ingress.yaml
Labels: bug

#167 Bugfix/logs view not working
  apps/views.py
  templates/apps/logs.html
Labels: bug

#168 SS 963 install fixtures only if changed
  common/management/commands/install_fixtures.py
  common/migrations/0003_fixtureversion.py
  common/models.py
  scripts/run_web.sh
Labels: new feature, change

#169 SS 871 Authentication token expiry
  Dockerfile
  api/APIpermissions.py
  api/views.py
  portal/views.py
  studio/settings.py
Labels: enhancement, security

#172 SS-940 replace prints with logs
  api/APIpermissions.py
  api/openapi/common_api.py
  api/openapi/lookups_api.py
  api/openapi/public_apps_api.py
  api/tests/test_openapi.py
  api/tests/test_openapi_public_apps.py
  api/views.py
  apps/controller.py
  apps/generate_form.py
  apps/helpers.py
  apps/serialize.py
  apps/tasks.py
  apps/views.py
  models/helpers.py
  models/models.py
  models/templatetags/custom_tags.py
  models/views.py
  portal/views.py
  projects/models.py
  projects/tasks.py
  projects/views.py
  studio/system_version.py
  studio/views.py
Labels: enhancement

#173 Added collections functionality
  apps/models.py
  collections_module/__init__.py
  collections_module/admin.py
  collections_module/apps.py
  collections_module/migrations/0001_initial.py
  collections_module/migrations/__init__.py
  collections_module/models.py
  collections_module/tests.py
  collections_module/urls.py
  collections_module/views.py
  cypress/e2e/ui-tests/test-public-models-page.cy.js
  cypress/e2e/ui-tests/test-views-as-reader.cy.js
  portal/models.py
  portal/views.py
  studio/migrations/apps/0006_appinstance_collections.py
  studio/migrations/portal/0002_publishedmodel_collections.py
  studio/settings.py
  studio/urls.py
  templates/collections/collection.html
  templates/common/app_card.html
  templates/common/model_card.html
  templates/models/index.html
  templates/portal/apps.html
Labels: new feature

#175 Added instructions for running apps locally to the public apps page
  portal/views.py
  static/css/serve-elements.css
  templates/collections/collection.html
  templates/common/app_card.html
  templates/common/app_card_description.html
  templates/common/app_card_docker_info.html
  templates/portal/apps.html
  templates/portal/home.html
Labels: new feature

#177 Changed default admin email to being dynamically set via env variable
  .env.template
  scripts/admin_token.py
Labels: security
