Repository ScilifelabDataCentre/serve, pull requests merged in 2024-01, with the labels that each got.

#125 Feature/minio file upload
  Dockerfile
  apps/tasks.py
  apps/views.py
  charts/apps/minio/chart/templates/deployment.yaml
  charts/apps/minio/chart/templates/ingress.yaml
  charts/apps/minio/chart/templates/project-s3-ingress.yaml
  charts/apps/minio/chart/templates/secret.yaml
  charts/apps/minio/chart/templates/service.yaml
  charts/apps/minio/chart/values.yaml
  charts/apps/rstudio/chart/values.yaml
  common/management/__init__.py
  common/management/commands/__init__.py
  common/management/commands/add_locust_users.py
  common/management/commands/create_locust_apps.py
  common/management/commands/create_locust_projects.py
  common/management/commands/delete_locust_projects.py
  common/management/commands/remove_locust_users.py
  customtags/templatetags/get_dict_key.py
  fixtures/appcats_fixtures.json
  fixtures/apps_fixtures.json
  fixtures/projects_templates.json
  projects/views.py
  studio/settings.py
  templates/apps/create.html
  templates/apps/update.html
  templates/base.html
  templates/projects/overview.html
Labels: new feature

#124 Additional UI bugfixes
  apps/views.py
  projects/views.py
  templates/apps/create.html
  templates/apps/update.html
  templates/projects/project_create.html
Labels: bug

#126 Allow shinyproxy iframes
  charts/apps/shinyproxy/chart/templates/configmap.yaml
Labels: bug

#131 Additional new user categories need to go through manual verification
  .github/workflows/e2e-tests.yaml
  common/forms.py
  common/tests.py
  static/js/form-helpers.js
Labels: enhancement

#127 Integration of new event listener
  api/APIpermissions.py
  apps/tasks.py
  apps/views.py
  docker-compose.yaml
  scripts/admin_token.py
  templates/apps/create.html
Labels: bug, new feature

#132 Added new privacy type on backend side
  apps/helpers.py
  apps/serialize.py
  apps/views.py
  charts/apps/custom-app/chart/templates/ingress.yaml
  charts/apps/custom-app/config.json
  charts/apps/dash/chart/templates/ingress.yaml
  charts/apps/dash/config.json
  charts/apps/jupyter-lab/config.json
  charts/apps/minio/config.json
  charts/apps/mlflow-serve/config.json
  charts/apps/mlflow/config.json
  charts/apps/python-serve/chart/templates/ingress.yaml
  charts/apps/python-serve/config.json
  charts/apps/pytorch-serve/chart/templates/ingress.yaml
  charts/apps/pytorch-serve/config.json
  charts/apps/rstudio/config.json
  charts/apps/shiny/chart/templates/ingress.yaml
  charts/apps/shiny/config.json
  charts/apps/shinyproxy/chart/templates/ingress.yaml
  charts/apps/shinyproxy/config.json
  charts/apps/tensorflow-serve/chart/templates/ingress.yaml
  charts/apps/tensorflow-serve/config.json
  charts/apps/volumeK8s/config.json
  charts/apps/vscode/config.json
  fixtures/apps_fixtures.json
  portal/views.py
Labels: new feature

#137 Fixed release name ----generated---- bug
  apps/views.py
Labels: bug
