Repository ScilifelabDataCentre/serve, pull requests merged in 2024-09, with the labels that each got.

#219 SS-1088 Add 500 page when everything breaks
  templates/500.html
  templates/base.html
  templates/common/navbar.html
Labels: enhancement

#221 SS-1086 Added advanced input group to the shiny apps with site_dir option
  apps/forms/base.py
  apps/forms/field/widget.py
  apps/forms/shiny.py
  apps/migrations/0010_shinyinstance_shiny_site_dir.py
  apps/models/app_types/shiny.py
  templates/apps/create_base.html
  templates/apps/custom_field.html
  templates/apps/partials/div_label_with_help_toggle.html
  templates/apps/partials/srv_prepend_append_input_group.html
Labels: new feature

#207 SS-1049 pycharm dev setup
  .gitignore
  README.md
  docker-compose.yaml
  local.Dockerfile
Labels: enhancement

#224 Added acknowledgement text and replaced MinIO with filebrowser information
  templates/portal/about.html
Labels: change

#223 SS-1108 environment support in jupyter notebooks
  apps/constants.py
  apps/forms/jupyter.py
  apps/migrations/0011_jupyterinstance_environment.py
  apps/models/app_types/jupyter.py
  cypress/e2e/setup-scripts/seed_superuser.py
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  fixtures/projects_templates.json
  projects/migrations/0002_alter_environment_app_alter_environment_image_and_more.py
  projects/migrations/0003_alter_environment_rename_jupyter_lab_to_default_jupyter.py
  projects/models.py
  templates/projects/settings.html
Labels: change

#226 SS-1101 Add password help text to the signup and password reset forms
  common/forms.py
  templates/registration/password_reset_confirm.html
  templates/registration/signup.html
Labels: change

#227 App status enhancements
  api/views.py
  apps/helpers.py
  apps/models/base/base.py
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  studio/urls.py
Labels: enhancement

#229 SS-1089 Add connection pooling
  common/context_processors.py
  poetry.lock
  pyproject.toml
  studio/settings.py
Labels: bug, enhancement

#225 SS-674 add event announcements functionality
  portal/admin.py
  portal/migrations/0002_eventsobject.py
  portal/models.py
  portal/urls.py
  portal/views.py
  projects/admin.py
  templates/common/footer.html
  templates/events/events.html
  templates/portal/home.html
Labels: new feature

#230 Change display of prepend text for `shiny_site_dir`
  apps/forms/shiny.py
Labels: bug

#232 SS-1125 Added environment support for rstudio
  apps/forms/rstudio.py
  apps/migrations/0012_rstudioinstance_environment.py
  apps/models/app_types/rstudio.py
  fixtures/projects_templates.json
  projects/migrations/0004_add_rstudio_environment_to_old_projects.py
Labels: new feature
