Repository ScilifelabDataCentre/serve, pull requests merged in 2024-02, with the labels that each got.

#134 Added basic logs view for users
  apps/urls.py
  apps/views.py
  static/css/serve-utilities.css
  templates/apps/logs.html
  templates/common/common_head.html
  templates/projects/overview.html
Labels: enhancement

#139 SS 893 manual publish step
  .github/workflows/ci.yaml
  .github/workflows/e2e-tests.yaml
  .github/workflows/pre-commit.yaml
  .github/workflows/publish.yaml
Labels: new feature, cicd

#136 Added mount path settings and uid for custom apps
  apps/controller.py
  apps/helpers.py
  apps/tasks.py
  apps/views.py
  charts/apps/custom-app/chart/templates/deployment.yaml
  charts/apps/custom-app/config.json
  fixtures/apps_fixtures.json
  static/css/dataTables.bootstrap5.min.css
  static/js/dataTables.bootstrap5.min.js
  static/js/jquery.dataTables.min.js
  templates/apps/create.html
  templates/apps/logs.html
  templates/apps/update.html
  templates/common/common_head.html
Labels: enhancement

#143 Bugfix/userid storage item javascript error
  static/css/dataTables.bootstrap5.min.css
  templates/apps/create.html
  templates/apps/logs.html
  templates/projects/overview.html
Labels: bug

#145 SS-907 Fixed update of long app status texts
  api/views.py
  apps/helpers.py
  apps/tests/test_update_status_handler.py
Labels: bug

#144 Fixed bug where minio crashed when bucket existed
  charts/apps/minio/chart/templates/deployment.yaml
Labels: bug

#146 Bugfix/admin action reset applimits
  apps/helpers.py
  apps/views.py
  charts/apps/custom-app/chart/templates/deployment.yaml
  projects/admin.py
Labels: bug, enhancement

#147 added warning about minio
  templates/apps/create.html
Labels: change

#138 SS 500 scan and secure
  .dockerignore
  Dockerfile
  apps/tasks.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: security, new feature

#150 SS 841 Add new app type TissUUmaps
  charts/apps/tissuumaps/chart/Chart.yaml
  charts/apps/tissuumaps/chart/templates/deployment.yaml
  charts/apps/tissuumaps/chart/templates/ingress.yaml
  charts/apps/tissuumaps/chart/templates/service.yaml
  charts/apps/tissuumaps/chart/templates/tissuumaps-configmap.yaml
  charts/apps/tissuumaps/chart/values.yaml
  charts/apps/tissuumaps/config.json
  docker-compose.yaml
  fixtures/apps_fixtures.json
  static/images/logos/apps/tissuumaps-logo.svg
Labels: new feature

#140 SS 817 setup django logging
  .env.template
  .github/workflows/ci.yaml
  docker-compose.yaml
  poetry.lock
  portal/views.py
  pyproject.toml
  studio/middleware.py
  studio/settings.py
  studio/utils.py
Labels: enhancement, new feature

#142 SS 817 celery worker logging
  apps/tasks.py
  studio/celery.py
  studio/settings.py
  studio/utils.py
Labels: new feature

#148 Increased e2e test coverage to superuser functionality, file management, app statuses, signup form
  .github/pull_request_template.md
  cypress/e2e/setup-scripts/seed_contributor.py
  cypress/e2e/setup-scripts/seed_superuser.py
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-project-as-superuser.cy.js
  cypress/e2e/ui-tests/test-public-webpages.cy.js
  cypress/e2e/ui-tests/test-signup.cy.js
  cypress/fixtures/users.json
  projects/views.py
  templates/registration/signup.html
Labels: bug, cicd

#152 SS-841 Polishing app type tissuumaps
  charts/apps/tissuumaps/chart/values.yaml
  fixtures/apps_fixtures.json
  studio/settings.py
  templates/apps/create.html
Labels: new feature

#151 SS-861 remove user info from urls
  apps/tests/test_app_settings_view.py
  apps/tests/test_app_view_forbidden.py
  apps/tests/test_create_app_view.py
  apps/tests/test_delete_app_view.py
  apps/tests/test_get_status_view.py
  apps/views.py
  cypress/e2e/setup-scripts/seed_contributor.py
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-project-as-superuser.cy.js
  projects/tests/test_grant_access_to_project_view.py
  projects/tests/test_project_create_view.py
  projects/tests/test_project_view.py
  projects/tests/test_revoke_access_to_project_view.py
  projects/tests/test_update_pattern_view.py
  projects/urls.py
  projects/views.py
  studio/urls.py
  templates/apps/create.html
  templates/apps/update.html
  templates/projects/grant_revoke_access.html
  templates/projects/index.html
  templates/projects/overview.html
  templates/projects/pattern_selector.html
  templates/projects/settings.html
Labels: security, change

#153 Add requirement for unique docker image tags for each version of depoyed apps
  charts/apps/custom-app/chart/templates/deployment.yaml
  charts/apps/dash/chart/templates/deployment.yaml
  charts/apps/python-serve/chart/templates/deployment.yaml
  charts/apps/shiny/chart/templates/deployment.yaml
  charts/apps/shinyproxy/chart/templates/configmap.yaml
  charts/apps/tissuumaps/chart/templates/deployment.yaml
  templates/apps/create.html
  templates/apps/update.html
Labels: change

#155 SS 917 file transfer
  apps/tasks.py
  apps/views.py
  charts/apps/filemanager/chart/Chart.yaml
  charts/apps/filemanager/chart/templates/deployment.yaml
  charts/apps/filemanager/chart/templates/ingress.yaml
  charts/apps/filemanager/chart/templates/service.yaml
  charts/apps/filemanager/chart/values.yaml
  charts/apps/filemanager/config.json
  charts/apps/filemanager/logo.png
  charts/apps/minio/chart/Chart.yaml
  charts/apps/minio/chart/templates/deployment.yaml
  charts/apps/minio/chart/templates/secret.yaml
  charts/apps/minio/chart/templates/service.yaml
  charts/apps/minio/chart/values.yaml
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  docker-compose.yaml
  fixtures/apps_fixtures.json
  poetry.lock
  projects/views.py
  pyproject.toml
  static/images/logos/apps/filemanager-logo.svg
  templates/apps/create.html
  templates/projects/overview.html
Labels: bug, new feature, cicd

#156 SS-690 new privacy type
  apps/generate_form.py
  apps/helpers.py
  apps/models.py
  apps/serialize.py
  apps/tests/test_app_settings_view.py
  apps/tests/test_create_app_view.py
  apps/views.py
  charts/apps/custom-app/chart/templates/ingress.yaml
  charts/apps/custom-app/config.json
  charts/apps/dash/chart/templates/ingress.yaml
  charts/apps/dash/config.json
  charts/apps/filemanager/config.json
  charts/apps/jupyter-lab/config.json
  charts/apps/mlflow-serve/config.json
  charts/apps/mlflow/config.json
  charts/apps/python-serve/chart/templates/ingress.yaml
  charts/apps/python-serve/config.json
  charts/apps/pytorch-serve/chart/templates/ingress.yaml
  charts/apps/pytorch-serve/config.json
  charts/apps/rstudio/config.json
  charts/apps/shiny/chart/templates/ingress.yaml
  charts/apps/shiny/config.json
  charts/apps/shinyproxy/chart/templates/ingress.yaml
  charts/apps/shinyproxy/config.json
  charts/apps/tensorflow-serve/chart/templates/ingress.yaml
  charts/apps/tensorflow-serve/config.json
  charts/apps/volumeK8s/config.json
  charts/apps/vscode/config.json
  fixtures/apps_fixtures.json
  portal/views.py
  static/js/apps_form.js
  studio/migrations/apps/0003_appinstance_note_on_linkonly_privacy.py
  studio/migrations/apps/0004_remove_appinstance_note_on_linkonly_privacy.py
  studio/migrations/apps/0005_appinstance_note_on_linkonly_privacy.py
  templates/apps/create.html
  templates/apps/update.html
Labels: enhancement

#158 SS 880 Brute force protection to handle repeated login failures
  conftest.py
  cypress/e2e/db-seed-brute-force-login-user.sh
  cypress/e2e/setup-scripts/seed_brute_force_login_user.py
  cypress/e2e/ui-tests/test-brute-force-login-attempts.cy.js
  cypress/fixtures/users.json
  cypress/support/commands.js
  package-lock.json
  poetry.lock
  pyproject.toml
  studio/settings.py
  templates/registration/locked_out.html
Labels: security, new feature

#160 SS-933 Automatic logout of inactive users
  studio/settings.py
Labels: enhancement, security

#159 Added project template to project model and fixed UI
  fixtures/projects_templates.json
  projects/admin.py
  projects/models.py
  projects/views.py
  studio/migrations/projects/0002_project_project_template.py
  templates/projects/overview.html
Labels: bug
