Repository ScilifelabDataCentre/serve, pull requests merged in 2025-06, with the labels that each got.

#326 SS-1282 revamp homepage
  cypress/e2e/ui-tests/test-collections.cy.js
  cypress/e2e/ui-tests/test-public-webpages.cy.js
  cypress/e2e/ui-tests/test-user-manage-apps.cy.js
  portal/views.py
  static/css/serve-elements.css
  static/css/serve-utilities.css
  static/images/api.png
  static/images/predgui.png
  static/images/shiny-app.png
  templates/common/app_card_docker_info.html
  templates/common/common_head.html
  templates/common/footer.html
  templates/common/navbar.html
  templates/portal/home.html
Labels: enhancement

#332 SS-1391 Integration tests against Kubernetes with Django endpoints
  cypress.config.js
  cypress/e2e/integration-tests/test-deploy-app.cy.js
Labels: cicd

#330 SS-1411 Create schema org description function and app metadata landing page
  apps/helpers.py
  apps/tests/test_app_helper_utils.py
  apps/urls.py
  apps/views.py
  common/tests/__init__.py
  common/tests/manage_test_data.py
  common/tests/tests.py
  common/tests/tests_security_test_data_population_views.py
  common/views.py
  cypress/e2e/ui-tests/test-public-webpages.cy.js
  poetry.lock
  pyproject.toml
  templates/common/app_card.html
  templates/common/app_metadata.html
Labels: new feature

#340 SS-613 public apps filter and search
  apps/migrations/0031_baseappinstance_k8s_values_override_and_more.py
  apps/migrations/0032_subdomainadmin.py
  apps/migrations/0033_alter_k8suserappstatus_status.py
  apps/migrations/0034_tagulous_depictioinstance_tags_depictioinstance_and_more.py
  models/templatetags/custom_tags.py
  portal/views.py
  static/css/serve-utilities.css
  static/js/list.min.js
  templates/base.html
  templates/common/app_card.html
  templates/common/common_head.html
  templates/common/navbar.html
  templates/portal/apps.html
Labels: new feature

#354 SS-1477 optimize public apps page
  portal/views.py
  static/css/serve-elements.css
  templates/common/app_card.html
  templates/portal/apps.html
Labels: bug

#353 Add admin view links for authenticated staff users in project and app templates
  apps/views.py
  projects/views.py
  studio/urls.py
  templates/apps/create_base.html
  templates/projects/partials/project_description.html
  templates/projects/partials/project_header.html
Labels: enhancement
