Repository ScilifelabDataCentre/serve, pull requests merged in 2025-05, with the labels that each got.

#320 SS-1219 Django views to manage e2e_test data
  common/management/manage_test_data.py
  common/tests_security_test_data_population_views.py
  common/urls.py
  common/views.py
  cypress.config.js
  cypress/e2e/ui-tests/test-brute-force-login-attempts.cy.js
  cypress/e2e/ui-tests/test-collections.cy.js
  cypress/e2e/ui-tests/test-login-account-handling.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-signup.cy.js
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  cypress/e2e/ui-tests/test-user-manage-apps.cy.js
  cypress/e2e/ui-tests/test-views-as-reader.cy.js
  cypress/support/commands.js
Labels: enhancement

#327 Hotfix/SS-1448 password log
  api/views.py
  static/js/password_validation.js
Labels: bug, security

#328 Setup gmail api as a backend for sending emails
  common/tasks.py
  common/views.py
  poetry.lock
  pyproject.toml
  studio/settings.py
  studio/views.py
Labels: bug

#333 SS -1442 Add API for Serve content stats
  api/openapi/content_stats_api.py
  api/openapi/urls.py
  api/tests/test_openapi_content_stats.py
Labels: new feature

#334 SS-1443 Internal content stats and review API
  api/tests/test_api.py
  api/urls.py
  api/views.py
Labels: new feature

#336 SS-1342 Update public apps API resource
  api/openapi/public_apps_api.py
  api/openapi/urls.py
  api/tests/test_openapi_public_apps.py
  apps/models/base/base.py
  apps/tests/test_app_instance.py
  studio/settings.py
Labels: change

#338 Add k8s user app status choices Running and Deleted
  apps/migrations/0033_alter_k8suserappstatus_status.py
  apps/models/base/k8s_user_app_status.py
Labels: change

#322 SS-1394 New app type (Depictio) in Serve
  apps/admin.py
  apps/app_registry.py
  apps/forms/__init__.py
  apps/forms/depictio.py
  apps/migrations/0034_tagulous_depictioinstance_tags_depictioinstance_and_more.py
  apps/models/app_types/__init__.py
  apps/models/app_types/depictio.py
  fixtures/apps_fixtures.json
  fixtures/projects_templates.json
  poetry.lock
  pyproject.toml
  scripts/run_web.sh
  static/images/logos/apps/depictio-logo.png
  studio/settings.py
  templates/projects/partials/app_templates.html
Labels: new feature
