Repository ScilifelabDataCentre/serve, pull requests merged in 2025-02, with the labels that each got.

#275 SS-964 Send email confirmation on project access
  projects/views.py
  studio/views.py
Labels: new feature

#277 SS-1236 fixing e2e test for new jupyterlab environments
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
Labels: enhancement

#280 SS-1288 mlflow default resources
  apps/models/app_types/mlflow.py
Labels: change

#278 SS-1204 harmonize frontend
  apps/forms/base.py
  apps/forms/filemanager.py
  cypress/e2e/ui-tests/test-brute-force-login-attempts.cy.js
  cypress/e2e/ui-tests/test-deploy-app.cy.js
  cypress/e2e/ui-tests/test-login-account-handling.cy.js
  cypress/e2e/ui-tests/test-project-as-contributor.cy.js
  cypress/e2e/ui-tests/test-public-webpages.cy.js
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  cypress/e2e/ui-tests/test-views-as-reader.cy.js
  static/css/serve-colors.css
  static/css/serve-elements.css
  static/css/serve-utilities.css
  templates/common/app_card.html
  templates/common/app_card_docker_info.html
  templates/common/navbar.html
  templates/portal/apps.html
  templates/projects/partials/app_instances_table.html
  templates/projects/partials/app_templates.html
  templates/projects/project_create.html
  templates/registration/password_change_form.html
  templates/registration/password_reset_form.html
  templates/registration/signup.html
  templates/user/profile.html
  templates/user/profile_edit_form.html
Labels: enhancement

#282 SS-1288 fix app status
  apps/models/app_types/mlflow.py
  fixtures/apps_fixtures.json
  static/images/logos/apps/mlflow-logo.png
Labels: change

#281 SS-889 App image docker hub autosuggestion
  api/urls.py
  api/utils.py
  api/views.py
  apps/forms/custom.py
  apps/forms/dash.py
  apps/forms/gradio.py
  apps/forms/mixins.py
  apps/forms/shiny.py
  apps/forms/streamlit.py
  studio/settings.py
  templates/apps/create_base.html
Labels: new feature

#279 SS-1288 Added secrets view for mlflow
  apps/admin.py
  apps/migrations/0024_apps_user_can_see_secrets.py
  apps/models/app_types/mlflow.py
  apps/models/base/app_template.py
  apps/signals.py
  apps/urls.py
  apps/views.py
  templates/apps/secrets_view.html
  templates/projects/partials/app_instances_table.html
Labels: new feature

#283 SS-1263 fixing number of apps displayed on public apps page
  portal/views.py
Labels: bug

#274 SS-1288 Add basic mlflow support
  apps/admin.py
  apps/app_registry.py
  apps/forms/mlflow.py
  apps/helpers.py
  apps/migrations/0022_mlflowinstance_apps_user_can_see_secrets.py
  apps/models/app_types/__init__.py
  apps/models/app_types/mlflow.py
  apps/models/base/app_template.py
  apps/signals.py
  apps/urls.py
  apps/views.py
  fixtures/apps_fixtures.json
  fixtures/projects_templates.json
  poetry.lock
  static/images/logos/apps/mlflow-logo.png
  templates/apps/secrets_view.html
  templates/projects/partials/app_instances_table.html
Labels: new feature

#286 Fix/shiny form path error
  apps/forms/shiny.py
Labels: bug

#287 SS-1288 Fix secrets view for mlflow
  apps/views.py
  projects/views.py
Labels: bug

#285 SS-1327 Add upload size in admin panel
  apps/admin.py
  apps/migrations/0028_baseappinstance_upload_size.py
  apps/models/base/base.py
  cypress/e2e/ui-tests/test-superuser-functionality.cy.js
  fixtures/projects_templates.json
Labels: enhancement

#291 FIX app_status query for mlflow view
  apps/views.py
Labels: bug
